spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/data/your_db_path
    username: sa
    password: your_db_password
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type: trace